### ISSUE TITLE
Any plan for support of Malayalam language?

### ISSUE THREAD

**Issue by debasish-mihup** [sutariyaraj/indic-num2words#11]
@raj-sutariya Can you add support for Malayalam language? I need to handle basic digits, fractions too.

**Comment by ByteJoseph** [comment]
I am a native Malayalam speaker. Let me give it a try

**Comment by debasish-mihup** [comment]
@raj-sutariya I have made changes for Malayalam support and multiple corrections in existing 4 Indian languages. I have already made a PR request. Kindle review and merge the same.
